In [4]:
import pandas as pd
import os
import empyrical

In [2]:
DATA_DIR = u'D:/workspace/zjsxzy_in_js/Research/期货策略/data/'

In [3]:
files = [f for f in os.listdir(DATA_DIR)]

In [7]:
dic = {}
for f in files:
    fname = u'%s/%s'%(DATA_DIR, f)
    temp = pd.read_excel(fname)
    dic[f.rstrip('.xlsx')] = temp['return']
df = pd.DataFrame(dic)

In [9]:
df.tail()

,10-100,10-105,10-110,10-115,10-120,10-125,10-130,10-135,10-140,10-145,...,9-54,9-59,9-64,9-69,9-74,9-79,9-84,9-89,9-94,9-99
2017-12-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-12-07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-12-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-12-11,0.000000,0.000000,0.000000,0.000000,0.000000,0.016516,0.000000,0.000000,0.000000,0.000000,...,0.016516,0.016516,0.016516,0.016516,0.016516,0.016516,0.016516,0.016516,0.016516,0.016516
2017-12-12,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,...,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143,-0.013143